name: 🐛 Bug report
description: Create a report to help us improve.
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior

  - type: textarea
    attributes:
      label: Actual behavior

  - type: textarea
    attributes:
      label: Code to reproduce
      description: JavaScript/TypeScript
      render: ts

  - type: input
    attributes:
      label: Package version
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have read the documentation
          required: true
        - label: I have tried my code with the latest version of Node.js and this package
          required: true
