name: 🚀 Feature request
description: Suggest an idea or feature.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have read the documentation
          required: true
        - label: I'm sure this feature doesn't already exist
          required: true
